### ISSUE TITLE
Add comparison with CWL

### ISSUE THREAD

**Issue by cmungall** [ihh/biomake-appnote#1]
http://www.commonwl.org/

From http://www.commonwl.org/v1.0/UserGuide.html#Introduction

_However unlike "make", CWL tasks are isolated and you must be explicit about your inputs and outputs_

CWL engines don't seem to build dependencies for you, it's up to the client to specify order of execution (AFAICT - will read more). As such, the distinctions between CWL and Biomake seem fairly clear.

**Comment by ihh** [comment]
True. We should make the comparison, and I think mention (as concisely as possible) that there are a lot of other bioinformatics workflow management systems out there, but they are not usually declarative.

There are also a lot of other make alternatives, including some in functional/parallel languages ([Erlang make](http://erlang.org/doc/man/make.html)) and/or offering features like MD5 triggers ([omake](http://omake.metaprl.org/index.html), [makepp](http://makepp.sourceforge.net/)) or SGE support ([qmake](http://gridscheduler.sourceforge.net/htmlman/htmlman1/qmake.html)). Some of these are quite close to biomake, but none offers the full feature set.

There are also several defunct make-alternatives like PostMake which worked on a Postgres database... can't find a link for it now, though.

**Comment by ihh** [comment]
fixed by e408254
